# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BnPIwQ2h_PaUJ-qw-5_GWMxGWyWUxxzt
"""

!pip install streamlit

!pip install mftool

!pip install yahoo_fin

!pip install cryptocmd

import streamlit as st
import pandas as pd
import requests
from plotly import graph_objs as go
import yfinance as yf
from mftool import Mftool
import datetime
import cufflinks as cf
cf.go_offline()
cf.set_config_file(offline=False, world_readable=True)
from yahoo_fin import stock_info as si
import streamlit as st
from cryptocmd import CmcScraper
from plotly import graph_objs as go
import time

